package com.testmu.agent.generation;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.testmu.agent.generation.model.GeneratedTestCase;
import com.testmu.agent.generation.model.GeneratedTestSuite;
import com.testmu.config.ConfigManager;
import com.testmu.config.FrameworkConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.stream.Collectors;

public class GeneratedTestWriter {

    private static final Logger LOG = LoggerFactory.getLogger(GeneratedTestWriter.class);
    private static final DateTimeFormatter TS = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private final FrameworkConfig config = ConfigManager.get();
    private final ObjectMapper objectMapper = new ObjectMapper()
            .registerModule(new JavaTimeModule())
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

    public Path write(GeneratedTestSuite suite) throws IOException {
        Path outputDir = Path.of(config.aiTestGenerationOutputDir());
        Files.createDirectories(outputDir);

        String packageName = "com.testmu.tests.generated";
        String javaSource = buildJavaSource(packageName, suite);
        Path javaFile = outputDir.resolve(suite.getClassName() + ".java");
        Files.writeString(javaFile, javaSource, StandardCharsets.UTF_8);

        Path manifestDir = Path.of(config.aiAgentMemoryPath(), "generated-tests");
        Files.createDirectories(manifestDir);
        Path manifest = manifestDir.resolve(suite.getClassName() + ".json");
        objectMapper.writerWithDefaultPrettyPrinter().writeValue(manifest.toFile(), suite);

        LOG.info("Generated test class written: {}", javaFile.toAbsolutePath());
        return javaFile;
    }

    private String buildJavaSource(String packageName, GeneratedTestSuite suite) {
        Set<String> imports = new LinkedHashSet<>();
        imports.add("org.testng.Assert");
        imports.add("org.testng.annotations.Test");
        imports.add(suite.getBaseClass().contains("API")
                ? "com.testmu.core.BaseAPITest"
                : "com.testmu.core.BaseUITest");
        imports.add("com.testmu.testdata.TestGroups");
        imports.addAll(suite.getImports());

        String importBlock = imports.stream()
                .map(i -> "import " + i + ";")
                .collect(Collectors.joining("\n"));

        String methods = suite.getTests().stream()
                .map(this::buildMethod)
                .collect(Collectors.joining("\n\n"));

        return """
                package %s;

                // AI-generated by TestGenerationAgent on %s
                // Module: %s | Provider: %s | Model: %s

                %s

                public class %s extends %s {

                %s
                }
                """.formatted(
                packageName,
                LocalDateTime.now().format(TS),
                suite.getModule(),
                config.aiProvider(),
                config.aiModel(),
                importBlock,
                suite.getClassName(),
                suite.getBaseClass().contains("API") ? "BaseAPITest" : "BaseUITest",
                methods
        );
    }

    private String buildMethod(GeneratedTestCase test) {
        String groups = test.getGroups().stream()
                .map(g -> "TestGroups." + toConstant(g))
                .collect(Collectors.joining(", "));

        String body = indentMethodBody(test.getMethodBody());

        return """
                    @Test(groups = {%s},
                            description = "%s")
                    public void %s() {
                %s
                    }""".formatted(
                groups,
                escape(test.getDescription()),
                test.getMethodName(),
                body
        );
    }

    private String indentMethodBody(String body) {
        if (body == null || body.isBlank()) {
            return "        Assert.fail(\"Empty generated test body\");";
        }
        String trimmed = body.strip();
        if (trimmed.startsWith("{") && trimmed.endsWith("}")) {
            trimmed = trimmed.substring(1, trimmed.length() - 1).strip();
        }
        return trimmed.lines()
                .map(line -> "        " + line.strip())
                .collect(Collectors.joining("\n"));
    }

    private String toConstant(String group) {
        return group.toUpperCase().replace("-", "_");
    }

    private String escape(String text) {
        return text == null ? "" : text.replace("\"", "\\\"");
    }
}
